version: "3"

services:
    nodeosd:
        build:
            dockerfile: ./eos.dockerfile
            context: .
        image: sagansoftware/eos:latest
        hostname: nodeosd
        entrypoint: nodeos
        command: >
            --data-dir /eos/build/data-dir
            --config-dir /eos/build/data-dir
            --http-alias=nodeosd:8888
            --http-alias=127.0.0.1:8888
            --http-alias=localhost:8888
            --http-alias=nodeosd:8889
            --http-alias=127.0.0.1:8889
            --http-alias=localhost:8889
        ports:
            - 8888:8888
            - 8889:8889
            - 9876:9876
        expose:
            - "8888"
            - "8889"
        volumes:
            - ./config.ini:/eos/build/data-dir/config.ini:ro
            - ./cert.pem:/eos/cert.pem:ro
            - ./key.pem:/eos/key.pem:ro
            - nodeos-data-volume:/opt/eosio/bin/data-dir
        cap_add:
            - IPC_LOCK
        stop_grace_period: 10m

    keosd:
        build:
            dockerfile: ./eos.dockerfile
            context: .
        image: sagansoftware/eos:latest
        hostname: keosd
        entrypoint: keosd
        command: >
            --wallet-dir /opt/eosio/bin/data-dir
            --unlock-timeout 9999999
            --http-server-address=127.0.0.1:8900
            --http-alias=keosd:8900
            --http-alias=localhost:8900
        ports:
            - 8900:8900
        expose:
            - "8900"
        volumes:
            - keosd-data-volume:/opt/eosio/bin/data-dir
            - ../target/wasm32-unknown-unknown/release:/mnt/dev/release:ro
            - ../examples:/mnt/dev/examples:ro
            - ../:/mnt/dev/project:ro
        links:
            - nodeosd
        stop_grace_period: 10m

volumes:
    nodeos-data-volume:
        external: true
    keosd-data-volume:
        external: true
