[package]
name = "util"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.3"
